"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# i will use a recursive function to find the fibonacci numbers using a while loop with the condition that the value is below 4 million
# then check if the fib number is even and if so add it to them sum

def SumOfEvenFib():

    sum = 0
    first = 0
    second = 1
    temp = 0

    while second < 4000000:
        if second % 2 == 0:
            sum += second

        temp = first + second
        first = second
        second = temp

    print("The sum of all even fibonacci numbers under 4 million is",sum)
    

if __name__ == "__main__":
    SumOfEvenFib()


